# Generated by Django 5.1.2 on 2024-10-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('km', 'km'), ('mi', 'miles')], default='km', max_length=2)),
                ('time', models.TimeField(blank=True, null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.meet')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DurationField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.team')),
            ],
        ),
    ]
