# Generated by Django 5.1.2 on 2024-10-11 03:52

from django.db import migrations

def add_conferences(apps, schema_editor):
    Conference = apps.get_model('racing', 'Conference')
    
    conferences = [
        {
            'full_name': 'Atlantic University Sport',
            'short_name': 'AUS',
        },
        {
            'full_name': 'Réseau du sport étudiant du Québec',
            'short_name': 'RSEQ',
        },
        {
            'full_name': 'Ontario University Athletics',
            'short_name': 'OUA',
        },
        {
            'full_name': 'Canada West',
            'short_name': 'CW',
        },
    ]
    
    for conf_data in conferences:
        Conference.objects.create(
            full_name=conf_data['full_name'],
            short_name=conf_data['short_name'],
        )

def add_aus_teams(apps, schema_editor):
    Team = apps.get_model('racing', 'Team')
        
    teams = [
        ('Dalhousie Tigers', 'DAL'),
        ('UNB Reds', 'UNB'),
        ('St. F X', 'StFX'),
        ('UPEI Panthers', 'UPEI'),
        ('Moncton Aigles Bleu', 'UdeM'),
        ("St. Mary's Huskies", 'SMU'),
        ('Acadia', 'Acadia'),
    ]
    
    for full_name, short_name in teams:
        Team.objects.create(full_name=full_name, short_name=short_name)


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_aus_teams),
        migrations.RunPython(add_conferences),
    ]
