# Generated by Django 5.1.2 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_auto_20241011_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], default='X', max_length=1),
        ),
    ]
