# Generated by Django 5.1.2 on 2024-10-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0005_runner_headshot_result_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
