# Generated by Django 5.1.2 on 2024-10-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0006_runner_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='slug',
            field=models.SlugField(),
        ),
    ]
