# Generated by Django 5.1.2 on 2024-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0007_alter_runner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
