# Generated by Django 5.1.2 on 2024-10-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0009_populate_meet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
