# Generated by Django 5.1.2 on 2024-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0010_alter_meet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
