# Generated by Django 5.1.2 on 2024-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0011_alter_team_full_name_alter_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='conference_logos'),
        ),
    ]
