# Generated by Django 5.1.2 on 2024-11-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0012_conference_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='conference',
        ),
        migrations.AddField(
            model_name='meet',
            name='conferences',
            field=models.ManyToManyField(to='racing.conference'),
        ),
    ]
