# Generated by Django 5.1.2 on 2024-11-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0013_remove_meet_conference_meet_conferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.runner')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Headshot',
        ),
    ]
