# Generated by Django 5.1.2 on 2024-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0014_rosterspot_delete_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed')], default='X', max_length=1),
        ),
    ]
