# Generated by Django 5.1.2 on 2024-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0017_alter_result_race_alter_result_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
