# Generated by Django 5.1.2 on 2024-11-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0018_alter_runner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
