# Generated by Django 5.1.2 on 2024-11-10 17:01

from django.db import migrations, models

def add_slug_to_aus_teams(apps, schema_editor):
    Team = apps.get_model('racing', 'Team')

    slug_map = {
        'Dalhousie Tigers': 'dalhousie',
        'UNB Reds': 'unb',
        'St. F X': 'stfx',
        'UPEI Panthers': 'upei',
        'Moncton Aigles Bleu': 'moncton',
        "St. Mary's Huskies": 'st-marys',
        'Acadia': 'acadia',
    }
    for full_name, slug in slug_map.items():
        Team.objects.filter(full_name=full_name).update(slug=slug)

class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0019_team_slug'),
    ]

    operations = [
        migrations.RunPython(add_slug_to_aus_teams),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
