# Generated by Django 5.1.2 on 2024-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0020_alter_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
