# Generated by Django 5.1.2 on 2024-11-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0021_alter_team_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=12),
        ),
    ]
