# Generated by Django 5.1.2 on 2024-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0022_alter_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='usports',
            field=models.BooleanField(default=False),
        ),
    ]
