# Generated by Django 5.1.2 on 2024-11-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0023_team_usports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='usports',
        ),
    ]
