# Generated by Django 5.1.2 on 2024-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0025_race_official_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('USPORTS', 'U Sports'), ('CLUB', 'Club'), ('HS', 'High School')], default='USPORTS', max_length=10),
        ),
    ]
