# Generated by Django 5.1.2 on 2024-11-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0026_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='displacers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='race',
            name='scorers',
            field=models.IntegerField(default=5),
        ),
    ]
