# Generated by Django 5.1.2 on 2024-11-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0028_remove_race_official_results_officialresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialresult',
            name='name',
            field=models.CharField(default='Official Results', max_length=50),
        ),
    ]
