# Generated by Django 5.1.2 on 2024-11-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0030_alter_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('OPEN', 'Open'), ('USPORTS', 'U Sports')], default='OPEN', max_length=50),
        ),
    ]
