# Generated by Django 5.1.2 on 2024-11-17 18:21

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0032_remove_rosterspot_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterspot',
            name='headshot',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='headshots'),
        ),
    ]
