# Generated by Django 5.1.2 on 2025-01-10 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0033_rosterspot_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='rival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racing.runner'),
        ),
    ]
