# Generated by Django 5.1.2 on 2025-01-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0034_runner_rival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='rival',
        ),
    ]
