# Generated by Django 5.1.2 on 2025-01-15 02:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0035_remove_runner_rival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='meet',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.ExtractYear('date'), models.F('slug'), name='unique_slug_year'),
        ),
    ]
