# Generated by Django 5.1.2 on 2025-01-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0036_alter_meet_slug_meet_unique_slug_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='tiebreaker',
            field=models.CharField(choices=[('LAST_SCORER', 'Last Scorer'), ('FIRST_DISPLACER', 'First Displacer')], default='FIRST_DISPLACER', max_length=50),
        ),
    ]
