[project]
name = "canada-xc"
version = "0.1.0"
description = "Django application for Canadian cross country running"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-htmx==1.29.0",
    "django-import-export==4.4.1",
    "django==6.1.1",
    "pillow==12.3.0",
    "psycopg[c]==3.3.4",
    "python-dotenv==1.2.3",
    "redis==8.1.0",
    "sorl-thumbnail==13.1.0",
    "thefuzz==0.22.1",
    "dj-database-url==3.1.2",
    "gunicorn==26.2.0",
    "sentry-sdk[django]==2.68.1",
    "whitenoise[brotli]==6.12.0",
    "django-storages[s3]==1.14.6",
]

[dependency-groups]
dev = [
    "bs4==0.0.2",
    "djade==1.9.0",
    "django-debug-toolbar==7.1.1",
    "requests==2.34.2",
    "ruff==0.16.10",
]

[tool.ruff]
exclude = ["**/migrations/*.py", "settings.py"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]

[tool.ruff.lint.isort]
known-first-party = ["canadaxc"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "django",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"django" = ["django"]
